title: mathpluslabs
description: Embedded Systems, Internet of Things and Prototyping Help
project_title: mathplusprototypes blog
theme: jekyll-theme-slate
markdown: kramdown
highlighter: rouge
google_analytics: [UA-142134024-1]